name: Autotesting

on:
  schedule:
    - cron: '0 3 * * 0'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest test_me.py

  build-and-test-app:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build .exe
        run: |
          pyinstaller --onefile test_me.py --name ComputerInfoApp

      - name: Test built app
        run: |
          ./dist/ComputerInfoApp.exe --test